version: '1'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "21017:21017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root